
            let computerScore = 0;
            let playerScore = 0;
            let i = 0;
            document.addEventListener(`click`, button);


            //random number generated by computer

            function computerPlay() {

                const computerOptions = [`rock`, `paper`, `scissors`]
                let randomAnswer = computerOptions[Math.floor(Math.random() * computerOptions.length)];
                console.log(randomAnswer);
                return randomAnswer;
            }

         
            //group all buttons together and return value as a string

            function button(e) { 
                const btn = document.getElementById(`button[id="${e}"]`)
                if (e.target.id === `rock` || e.target.id === `paper` || e.target.id === `scissors`) {
                    console.log(e.target.id);
                    
                    etar = e.target.id
                    test = computerPlay();

                    playRound(etar, test);
                    i++;
                    console.log(i);

                }

            }



            function playRound(playerSelection, computerSelection) {
               
                if (playerSelection === computerSelection) {
                     
                    console.log(`You tied this round!`);
                    return(`You tied this round!`)

                }   else if (playerSelection === `rock` && computerSelection === `scissors`) {
                    playerScore++;   
                    console.log (`You win! Rock beats Scissors`);
                    return (`You win! Rock beats Scissors`);

                }   else if (playerSelection === `scissors` && computerSelection === `rock`) {
                    computerScore++;   
                    console.log (`You lose! Rock beats Scissors`);
                    return (`You lose! Rock beats Scissors`);

                }   else if (playerSelection === `paper` && computerSelection === `scissors`) {
                    computerScore++;   
                    console.log (`You lose! Scissors beats paper`);
                    return (`You lose! Scissors beats paper`);


                }   else if (playerSelection === `scissors` && computerSelection === `paper`) {
                    playerScore++;     
                    console.log (`You win! Scissors beats Paper`);
                    return (`You win! Scissors beats Paper`);

                }
                
                else if (playerSelection === `rock` && computerSelection === `paper`) {
                    computerScore++;   
                    console.log (`You lose! Paper beats Rock`);
                    return (`You lose! Paper beats Rock`);

                }


                else if (playerSelection === `paper` && computerSelection === `rock`) {
                    playerScore++;   
                    console.log (`You win! Paper beats Rock`);
                    return (`You win! Paper beats Rock`);

                }
            }

            

        //play 3 rounds

        //     function play() {
        //             playRound();
        //             i++;
        //             console.log(playRound(playerPlay(), computerPlay()));
        //             console.log(`Computer score: ${computerScore}`);
        //             console.log(`Your score: ${playerScore}`);

        //             if (i !==3) {
        //                 play();

        //             } else {
        //             console.log(`GAME OVER`);
        //             }
        //         }

            
        // play();








           //button presses 

            // const rockButton = document.querySelector(`#rock`);
            // rockButton.addEventListener('click', playRound
            // });



            // const paperButton = document.querySelector(`#paper`);
            // paperButton.addEventListener('click', function(e){
            //     console.log(`paper`);
            //     return(`paper`);
            // });

            // const scissorsButton = document.querySelector(`#scissors`);
            // scissorsButton.addEventListener('click', function(e){
            //     console.log(`scissors`);
            //     return(`scissors`);
            // });
