
            let computerScore = 0;
            let playerScore = 0;
            let i = 0;
            document.addEventListener(`click`, button);


            //animating initial text

            const text = document.querySelector(`.intro-text`);
            const strText = text.textContent;
            const splitText = strText.split("");
            text.textContent = "";

            console.log(splitText);

            for (let i=0; i < splitText.length; i++) {
                text.innerHTML += "<span>"+ splitText[i] + "</span>";

            }
        
        
            //inserting letters one by one

            let char = 0;
            let timer = setInterval(onTick, 50);

            function onTick() {
                const span = text.querySelectorAll(`span`)[char];
                span.classList.add(`fade`);
                char++;
                if(char === splitText.length){
                    complete();
                    return;
                }
            }

            function complete() {
                clearInterval(timer); //does this need to be its own function?
                timer = null;
            }
            
        
            //hide all elements to show the end screen

            function hideMainContainer() {
                const hide = document.getElementById(`reveal`);
                const hideIntro = document.getElementById(`intro-text-hidden`);

                hide.classList.add(`hideMain`);
                hideIntro.classList.add(`hideMain`);

            } 



            //group all buttons together and return value as a string

            function button(e) { 
                const btn = document.getElementById(`button[id="${e}"]`);
                if (e.target.id === `rock` || e.target.id === `paper` || e.target.id === `scissors`) {
                    console.log(e.target.id);
                    
                    etar = e.target.id;
                    test = computerPlay();
                    
                if (computerScore !== 5 && playerScore !== 5)  {
                    playRound(etar, test);
                    i++;
                } 
            }

            }

            //random number generated by computer

            function computerPlay() {

                const computerOptions = [`rock`, `paper`, `scissors`]
                let randomAnswer = computerOptions[Math.floor(Math.random() * computerOptions.length)];
                console.log(randomAnswer);
                return randomAnswer;
            }

        

            //edit the player score tally box. One number increasing whenever the player wins a round.
            function playerUniformTally(playerScore) {

                let foo = document.getElementById(`score-tally`).innerHTML;
                foo = playerScore;
                document.getElementById(`score-tally`).innerHTML = foo;

           }

            //edit the computer score tally box. One number increasing whenever the computer wins a round.
           function computerUniformTally(computerScore) {

                let foo = document.getElementById(`computer-score-tally`).innerHTML;
                foo = computerScore;
                document.getElementById(`computer-score-tally`).innerHTML = foo;
            }   


            //Output by text the result of the round

            function textTally(textResult) {
                let foo = document.getElementById(`score-text`).innerHTML;
                foo = textResult;
                document.getElementById(`score-text`).innerHTML = foo;

            }

            //play again button (reset page)

            function refreshPage() {
                window.location.reload();
            }
            
            
            //Reset button created, styled (called on stylesheet.css), and appeneded to div
            
            let resetButton = document.createElement(`button`);
            resetButton.innerHTML = `PLAY AGAIN`;
            resetButton.classList.add(`reset-button`);
            let div = document.getElementById(`play-again`);



            //output the round number the player is on
            function roundTracker() {
                
                if (computerScore !== 5 && playerScore !== 5)  {
                    let bar = document.getElementById(`round-tracker`).innerHTML;
                    bar = `Round Number: ${i+1}`;
                    document.getElementById(`round-tracker`).innerHTML = bar;

                } else if (computerScore === 5){
                    hideMainContainer()

                    let finalText = document.createElement(`p`);
                    finalText.textContent = `THE COMPUTER WINS`;
                    finalText.classList.add(`final-text`);
                   // finalText.classList.add(`.intro-text`);


                    
                    let textContainer = document.getElementById(`final-text-container`);

                    textContainer.appendChild(finalText);
                    div.appendChild(resetButton);

                
                } else if (playerScore === 5){
                    hideMainContainer()

                    let finalText = document.createElement(`p`);
                    finalText.textContent = `YOU WIN`;
                    finalText.classList.add(`final-text`);
                    //finalText.classList.add(`.intro-text`);

                    let textContainer = document.getElementById(`final-text-container`);

                    textContainer.appendChild(finalText);
                    div.appendChild(resetButton);


                
                }

            }

            //Logic for comparing each round to determine a winner.
            function playRound(playerSelection, computerSelection) {

                if (playerSelection === computerSelection) {
                     
                    textTally(`You tied! Both you and the computer chose ${playerSelection}`);
                    roundTracker();
                   
                }else if (playerSelection === `rock` && computerSelection === `scissors`) {
                    playerScore++;   
                    playerUniformTally(playerScore);
                    textTally(`You win! Rock beats Scissors`);
                    roundTracker();

                

                }else if (playerSelection === `scissors` && computerSelection === `rock`) {
                    computerScore++;   
                    computerUniformTally(computerScore);
                    textTally(`You lose! Rock beats Scissors`);
                    roundTracker();

                   

                }else if (playerSelection === `paper` && computerSelection === `scissors`) {
                    computerScore++;   
                    computerUniformTally(computerScore);
                    textTally(`You lose! Scissors beats paper`);
                    roundTracker();



                }else if (playerSelection === `scissors` && computerSelection === `paper`) {
                    playerScore++;     
                    playerUniformTally(playerScore);
                    textTally(`You win! Scissors beats Paper`);
                    roundTracker();

                

                }else if (playerSelection === `rock` && computerSelection === `paper`) {
                    computerScore++;  
                    computerUniformTally(computerScore); 
                    textTally(`You lose! Paper beats Rock`);
                    roundTracker();


                }else if (playerSelection === `paper` && computerSelection === `rock`) {
                    playerScore++;   
                    playerUniformTally(playerScore);
                    textTally(`You win! Paper beats Rock`);
                    roundTracker();

                }
                
                


            }

            //When reset button clicked, reset the page and scores

            div.addEventListener(`click`, refreshPage);
            


