
            let computerScore = 0;
            let playerScore = 0;
            let i = 0;
            document.addEventListener(`click`, button);




            //group all buttons together and return value as a string

            function button(e) { 
                const btn = document.getElementById(`button[id="${e}"]`);
                if (e.target.id === `rock` || e.target.id === `paper` || e.target.id === `scissors`) {
                    console.log(e.target.id);
                    
                    etar = e.target.id;
                    test = computerPlay();
                    
                if (computerScore !== 5 && playerScore !== 5)  {
                    playRound(etar, test);
                    i++;
                } 
            }

            }

            //random number generated by computer

            function computerPlay() {

                const computerOptions = [`rock`, `paper`, `scissors`]
                let randomAnswer = computerOptions[Math.floor(Math.random() * computerOptions.length)];
                console.log(randomAnswer);
                return randomAnswer;
            }

        

            //edit the player score tally box. One number increasing whenever the player wins a round.
            function playerUniformTally(playerScore) {

                let foo = document.getElementById(`score-tally`).innerHTML;
                foo = playerScore;
                document.getElementById(`score-tally`).innerHTML = foo;

           }

            //edit the computer score tally box. One number increasing whenever the computer wins a round.
           function computerUniformTally(computerScore) {

                let foo = document.getElementById(`computer-score-tally`).innerHTML;
                foo = computerScore;
                document.getElementById(`computer-score-tally`).innerHTML = foo;
            }   


            //Output by text the result of the round

            function textTally(textResult) {
                let foo = document.getElementById(`score-text`).innerHTML;
                foo = textResult;
                document.getElementById(`score-text`).innerHTML = foo;

            }

            //play again button (reset page)

            function refreshPage() {
                window.location.reload();
            }

            //create button when game end

            function newGame() {


            }
            
            
            //Reset button created, styled (called on stylesheet.css), and appeneded to div
            
            let resetButton = document.createElement(`button`);
            resetButton.innerHTML = `PLAY AGAIN`;
            resetButton.classList.add(`reset-button`);
            let div = document.getElementById(`play-again`);



            //output the round number the player is on
            function roundTracker() {
                
                if (computerScore !== 5 && playerScore !== 5)  {
                    let bar = document.getElementById(`round-tracker`).innerHTML;
                    bar = `Round Number: ${i+1}`;
                    document.getElementById(`round-tracker`).innerHTML = bar;

                } else if (computerScore === 5){
                    let bar = document.getElementById(`round-tracker`).innerHTML;
                    bar = `THE COMPUTER WINS`;
                    document.getElementById(`round-tracker`).innerHTML = bar;
                    div.appendChild(resetButton);
                
                } else if (playerScore === 5){
                    let bar = document.getElementById(`round-tracker`).innerHTML;
                    bar = `YOU WIN THE GAME`;
                    document.getElementById(`round-tracker`).innerHTML = bar;  
                    div.appendChild(resetButton);

                
                }

            }

            //Logic for comparing each round to determine a winner.
            function playRound(playerSelection, computerSelection) {

                if (playerSelection === computerSelection) {
                     
                    textTally(`You tied! Both you and the computer chose ${playerSelection}`);
                    roundTracker();
                    //console.log(`You tied this round!`);
                    //return(`You tied this round!`)

                }else if (playerSelection === `rock` && computerSelection === `scissors`) {
                    playerScore++;   
                    playerUniformTally(playerScore);
                    textTally(`You win! Rock beats Scissors`);
                    roundTracker();

                   // console.log (`You win! Rock beats Scissors`);
                    //return (`You win! Rock beats Scissors`);

                }else if (playerSelection === `scissors` && computerSelection === `rock`) {
                    computerScore++;   
                    computerUniformTally(computerScore);
                    textTally(`You lose! Rock beats Scissors`);
                    roundTracker();

                    //console.log (`You lose! Rock beats Scissors`);
                    //return (`You lose! Rock beats Scissors`);

                }else if (playerSelection === `paper` && computerSelection === `scissors`) {
                    computerScore++;   
                    computerUniformTally(computerScore);
                    textTally(`You lose! Scissors beats paper`);
                    roundTracker();

                    //console.log (`You lose! Scissors beats paper`);
                    //return (`You lose! Scissors beats paper`);


                }else if (playerSelection === `scissors` && computerSelection === `paper`) {
                    playerScore++;     
                    playerUniformTally(playerScore);
                    textTally(`You win! Scissors beats Paper`);
                    roundTracker();

                    // console.log (`You win! Scissors beats Paper`);
                    // return (`You win! Scissors beats Paper`);

                }else if (playerSelection === `rock` && computerSelection === `paper`) {
                    computerScore++;  
                    computerUniformTally(computerScore); 
                    textTally(`You lose! Paper beats Rock`);
                    roundTracker();

                    //console.log (`You lose! Paper beats Rock`);
                    //return (`You lose! Paper beats Rock`);

                }else if (playerSelection === `paper` && computerSelection === `rock`) {
                    playerScore++;   
                    playerUniformTally(playerScore);
                    textTally(`You win! Paper beats Rock`);
                    roundTracker();

                    //console.log (`You win! Paper beats Rock`);
                    //return (`You win! Paper beats Rock`);

                }
                
                


            }

            //When reset button clicked, reset the page and scores

            div.addEventListener(`click`, refreshPage);
            

        //play 3 rounds

        //     function play() {
        //             playRound();
        //             i++;
        //             console.log(playRound(playerPlay(), computerPlay()));
        //             console.log(`Computer score: ${computerScore}`);
        //             console.log(`Your score: ${playerScore}`);

        //             if (i !==3) {
        //                 play();

        //             } else {
        //             console.log(`GAME OVER`);
        //             }
        //         }

            
        // play();


